### ISSUE TITLE
Have a button to “edit” the student's answer so the instructor can add on to incomplete ones or to refine them

### ISSUE THREAD

**Issue by Malika1109** [CMU-17313Q/fall23-nodebb-the-powerpuff-girls#24]
Estimated Effort:
Low - NodeBB employs an edit function for questions and answers so we just have to add onto it a little

Acceptance Criteria:
We will look to see if there is an “edit” button and if we make changes that they will be apparent in the answer

Component of #8

**Comment by ssaloos** [comment]
I was able to implement the edit button but was unable to meet the deadline due to lack of understanding of the codebase and how it is structured. I did not know how to connect the 'edit' button I added with the backend or with the specific user's privileges. One issue is that instead of the instructor being able to edit the student's response, my buggy code allowed the student to edit the instructor's response instead.
